from colorama import Fore, Back, Style, init
init(autoreset=True)

print("__COLORS__")
print(Fore.RED + "RED")
print(Fore.LIGHTRED_EX + "LIGHTRED_EX")
print(Fore.MAGENTA + "MAGENTA")
print(Fore.LIGHTMAGENTA_EX + "LIGHTMAGENTA_EX")
print(Fore.YELLOW + "YELLOW")
print(Fore.LIGHTYELLOW_EX + "LIGHTYELLOW_EX")
print(Fore.GREEN + "GREEN")
print(Fore.LIGHTGREEN_EX + "LIGHTGREEN_EX")
print(Fore.CYAN + "CYAN")
print(Fore.LIGHTCYAN_EX + "LIGHTCYAN_EX")
print(Fore.BLUE + "BLUE")
print(Fore.LIGHTBLUE_EX + "LIGHTBLUE_EX")
print(Fore.WHITE + "WHITE")
print(Fore.LIGHTWHITE_EX + "LIGHTWHITE_EX")
print(Fore.LIGHTBLACK_EX + "LIGHTBLACK_EX")
print(Fore.BLACK + "BLACK")

print()

print("__STYLES__")
print(Style.DIM + "DIM")
print(Style.NORMAL + "NORMAL")
print(Style.BRIGHT + "BRIGHT")

print()

print("__BACKGROUNDS__")
print(Back.BLUE + "               ")
print(Back.LIGHTBLUE_EX + "               ")
print(Back.CYAN + "               ")
print(Back.LIGHTCYAN_EX + "               ")
print(Back.RED + "               ")
print(Back.LIGHTRED_EX + "               ")
print(Back.MAGENTA + "               ")
print(Back.LIGHTMAGENTA_EX + "               ")
print(Back.YELLOW + "               ")
print(Back.LIGHTYELLOW_EX + "               ")
print(Back.GREEN + "               ")
print(Back.LIGHTGREEN_EX + "               ")
print(Back.BLACK + "              ")
print(Back.LIGHTBLACK_EX + "               ")
print(Back.WHITE + "               ")
print(Back.LIGHTWHITE_EX + "               ")


